from distutils.core import setup
setup(
  name = 'fpview',
  packages = ['fpview'],
  version = '0.1',
  description = 'Visualization tool for raw fingerprint data generated by NBIS',
  author = 'Zafar Takhirov',
  author_email = 'cc.rafaz@zafar.cc',
  url = 'https://github.com/zafartahirov/fpview',
  download_url = 'https://github.com/zafartahirov/fpview/tarball/0.1',
  keywords = ['biometric', 'fingerprint', 'NBIS', 'visualization'],
  classifiers = [],
)
